const data = {
  products: [
    {
      _id: '1',
      name: 'Orange Lengha',
      category: 'Mehandi',
      image: '/images/product1.jpg',
      price: 420,
      countInStock: 5,
      brand: 'Maria B',
      rating: 4.5,
      numReviews: 10,
      description: 'original product',
    },
    {
      _id: '2',
      name: 'Red Lengha',
      category: 'Walima',
      image: '/images/product2.jpg',
      price: 400,
      countInStock: 2,
      brand: 'ELAN',
      rating: 4.0,
      numReviews: 10,
      description: 'hand crafted chiffon product',
    },
    {
      _id: '3',
      name: 'Walima Blue Look',
      category: 'Walima',
      image: '/images/product3.jpg',
      price: 220,
      countInStock: 10,
      brand: 'Sana Safinaz',
      rating: 4.8,
      numReviews: 17,
      description: 'high quality product',
    },
    {
      _id: '4',
      name: 'Replica Nikkah Look',
      category: 'Nikkah',
      image: '/images/product4.jpg',
      price: 78,
      countInStock: 5,
      brand: 'Faisal and Co',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      _id: '5',
      name: 'MARIA',
      category: 'Pants',
      image: '/images/product1.jpg',
      price: 65,
      countInStock: 10,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '6',
      name: 'maria b',
      category: 'Pants',
      image: '/images/product3.jpg',
      price: 139,
      countInStock: 1,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
  ],
};
export default data;
